package co.spring.seguridad.persistencia.entidad;

public enum RolPermiso {
	
	USUARIO_VER_PERFIL,
	
	PRODUCTO_LEER_TODOS,
	PRODUCTO_LEER_UNO,
	PRODUCTO_CREAR,
	PRODUCTO_ACTUALIZAR,
	PRODUCTO_ELIMINAR,
	PRODUCTO_DESHABILITAR,
	
	CATEGORIA_LEER_TODOS,
	CATEGORIA_LEER_UNO,
	CATEGORIA_CREAR,
	CATEGORIA_ACTUALIZAR,
	CATEGORIA_ELIMINAR,
	CATEGORIA_DESHABILITAR,
}
